### ISSUE TITLE
Feedback tests

### ISSUE THREAD

**Issue by matiaslopezd** [Noheliajoeliana/backend-jr-hiring-main#5]
Hi @Noheliajoeliana! I'm here to give my feedback on your test!

# Test 1 
Excellent :heavy_check_mark:

# Test 2
Excellent :heavy_check_mark:

You catch errors! 🎊 Nice!!

# Test 3
Awesome :heavy_check_mark: 😱 👏🏻 

---

Well done using `try/catch`! But need to return a custom error because you can expose code in the response!! Is best to pass the error to monitoring platforms like Sentry and return something like `ServerError`.

As a general suggestion don't short variable names, write too much as you need! The code does not charge you per word hahaha! 😆

All it's awesome! congrats!! 🥇

**Comment by Noheliajoeliana** [comment]
Thank you @matiaslopezd ! I will take your advice into account🙈🙈
